package T20180904;

import java.util.HashMap;
import java.util.Map;

/**
 * LFU (Least Frequently Used) is a famous cache eviction algorithm.
 * <p>
 * For a cache with capacity k, if the cache is full and need to evict a key in it, the key with the lease frequently used will be kicked out.
 * <p>
 * Implement set and get method for LFU cache.
 */
public class LFUCacheIII {

    class Node {
        int key;
        int val;
        Node prev;
        Node next;
        TimedNode timedNode;

        Node(int key, int val) {
            this.key = key;
            this.val = val;
        }
    }

    class TimedNode {
        int times;
        Node head;
        Node tail;
        TimedNode next;

        public TimedNode(int times) {
            this.times = times;
        }
    }

    private Map<Integer, Node> nodeIndexes;//快速索引
    private int capacity;
    private TimedNode head;

    /*
     * @param capacity: An integer
     */
    public LFUCacheIII(int capacity) {
        // do intialization if necessary
        this.capacity = capacity;
        nodeIndexes = new HashMap<>(capacity);
    }

    private Node findRemovedNode() {
        if (head.head != null) {
            return head.head;
        } else {
            TimedNode next = head.next;
            while (next != null) {
                if (next.head != null) {
                    return next.head;
                }
                next = next.next;
            }
        }
        //never arrive here
        return null;
    }

    private void insert(Node newNode) {
        insert(1, newNode);
    }

    private void reset(Node node) {
        remove(node);
        insert(node.timedNode.times + 1, node);
    }

    private void remove(Node removedNode) {
        if (removedNode.prev == null) {//removedNode is head
            removedNode.timedNode.head = removedNode.next;
            if (removedNode.next == null) {
                removedNode.timedNode.tail = null;
            } else {
                removedNode.next.prev = null;
            }
            //todo:remove the empty TimedNode
        } else if (removedNode.next == null) {//removedNode is tail
            removedNode.prev.next = null;
            removedNode.timedNode.tail = removedNode.prev;
        } else {
            removedNode.prev.next = removedNode.next;
            removedNode.next.prev = removedNode.prev;
        }
        removedNode.prev = null;
        removedNode.next = null;
    }

    private void insert(int times, Node newNode) {
        if (head == null) {
            TimedNode newTimedNode = new TimedNode(times);
            head = newTimedNode;
            insert(newNode, newTimedNode);
            return;
        } else {
            TimedNode next = head;
            TimedNode pre = null;
            while (next != null) {
                if (next.times == times) {
                    insert(newNode, next);
                    return;
                } else if (next.times > times) {
                    if (pre == null) {
                        TimedNode newTimedNode = new TimedNode(times);
                        newTimedNode.next = head;
                        head = newTimedNode;
                        insert(newNode, newTimedNode);
                        return;
                    } else {
                        TimedNode newTimedNode = new TimedNode(times);
                        newTimedNode.next = pre.next;
                        pre.next = newTimedNode;
                        insert(newNode, newTimedNode);
                        return;
                    }
                }
                pre = next;
                next = next.next;
            }
            TimedNode newTimedNode = new TimedNode(times);
            pre.next = newTimedNode;
            insert(newNode, newTimedNode);
        }

    }

    private void insert(Node node, TimedNode timedNode) {
        node.timedNode = timedNode;
        if (timedNode.head == null) {
            timedNode.head = node;
            timedNode.tail = node;
        } else {
            timedNode.tail.next = node;
            node.prev = timedNode.tail;
            timedNode.tail = node;
        }
    }

    /*
     * @param key: An integer
     * @param value: An integer
     * @return: nothing
     */
    public void set(int key, int value) {
        // write your code here
        if (nodeIndexes.containsKey(key)) {
            Node oldNode = nodeIndexes.get(key);
            oldNode.val = value;
            reset(oldNode);
            return;
        }

        if (nodeIndexes.size() == capacity) {
            Node removedNode = findRemovedNode();
            if (removedNode.key == 96) {
                findRemovedNode();
            }
            remove(removedNode);
            nodeIndexes.remove(removedNode.key);
            return;
        }

        Node newNode = new Node(key, value);
        nodeIndexes.put(key, newNode);
        insert(newNode);
    }

    /*
     * @param key: An integer
     * @return: An integer
     */
    public int get(int key) {
        Node node = nodeIndexes.get(key);
        if (node == null) {
            return -1;
        } else {
            reset(node);
            return node.val;
        }
        // write your code here
    }

    public static void main(String[] args) {

        LFUCacheIII lfuCache = new LFUCacheIII(105);
        lfuCache.set(33, 219);

        System.out.println(lfuCache.get(39));
        lfuCache.set(96, 56);
        System.out.println(lfuCache.get(129));
        System.out.println(lfuCache.get(115));
        System.out.println(lfuCache.get(112));
        lfuCache.set(3, 280);
        System.out.println(lfuCache.get(40));
        lfuCache.set(85, 193);
        lfuCache.set(10, 10);
        lfuCache.set(100, 136);
        lfuCache.set(12, 66);
        lfuCache.set(81, 261);
        lfuCache.set(33, 58);
        System.out.println(lfuCache.get(3));
        lfuCache.set(121, 308);
        lfuCache.set(129, 263);
        System.out.println(lfuCache.get(105));
        lfuCache.set(104, 38);
        lfuCache.set(65, 85);
        lfuCache.set(3, 141);
        lfuCache.set(29, 30);
        lfuCache.set(80, 191);
        lfuCache.set(52, 191);
        lfuCache.set(8, 300);
        System.out.println(lfuCache.get(136));
        lfuCache.set(48, 261);
        lfuCache.set(3, 193);
        lfuCache.set(133, 193);
        lfuCache.set(60, 183);
        lfuCache.set(128, 148);
        lfuCache.set(52, 176);
        System.out.println(lfuCache.get(48));
        lfuCache.set(48, 119);
        lfuCache.set(10, 241);
        System.out.println(lfuCache.get(124));
        lfuCache.set(130, 127);
        System.out.println(lfuCache.get(61));
        lfuCache.set(124, 27);
        System.out.println(lfuCache.get(94));
        lfuCache.set(29, 304);
        lfuCache.set(102, 314);
        System.out.println(lfuCache.get(110));
        lfuCache.set(23, 49);
        lfuCache.set(134, 12);
        lfuCache.set(55, 90);
        System.out.println(lfuCache.get(14));
        System.out.println(lfuCache.get(104));
        lfuCache.set(77, 165);
        lfuCache.set(60, 160);
        System.out.println(lfuCache.get(117));
        lfuCache.set(58, 30);
        System.out.println(lfuCache.get(54));
        System.out.println(lfuCache.get(136));
        System.out.println(lfuCache.get(128));
        System.out.println(lfuCache.get(131));
        lfuCache.set(48, 114);
        System.out.println(lfuCache.get(136));
        lfuCache.set(46, 51);
        lfuCache.set(129, 291);
        lfuCache.set(96, 207);
        System.out.println(lfuCache.get(131));
        lfuCache.set(89, 153);
        lfuCache.set(120, 154);
        System.out.println(lfuCache.get(111));
        System.out.println(lfuCache.get(47));
        System.out.println(lfuCache.get(5));
        lfuCache.set(114, 157);
        lfuCache.set(57, 82);
        lfuCache.set(113, 106);
        lfuCache.set(74, 208);
        System.out.println(lfuCache.get(56));
        System.out.println(lfuCache.get(59));
        System.out.println(lfuCache.get(100));
        System.out.println(lfuCache.get(132));
        lfuCache.set(127, 202);
        System.out.println(lfuCache.get(75));
        lfuCache.set(102, 147);
        System.out.println(lfuCache.get(37));
        lfuCache.set(53, 79);
        lfuCache.set(119, 220);
        System.out.println(lfuCache.get(47));
        System.out.println(lfuCache.get(101));
        System.out.println(lfuCache.get(89));
        System.out.println(lfuCache.get(20));
        System.out.println(lfuCache.get(93));
        System.out.println(lfuCache.get(7));
        lfuCache.set(48, 109);
        lfuCache.set(71, 146);
        System.out.println(lfuCache.get(43));
        System.out.println(lfuCache.get(122));
        lfuCache.set(3, 160);
        System.out.println(lfuCache.get(17));
        lfuCache.set(80, 22);
        lfuCache.set(80, 272);
        System.out.println(lfuCache.get(75));
        System.out.println(lfuCache.get(117));
        lfuCache.set(76, 204);
        lfuCache.set(74, 141);
        lfuCache.set(107, 93);
        lfuCache.set(34, 280);
        lfuCache.set(31, 94);
        System.out.println(lfuCache.get(132));
        lfuCache.set(71, 258);
        System.out.println(lfuCache.get(61));
        System.out.println(lfuCache.get(60));
        lfuCache.set(69, 272);
        System.out.println(lfuCache.get(46));
        lfuCache.set(42, 264);
        lfuCache.set(87, 126);
        lfuCache.set(107, 236);
        lfuCache.set(131, 218);
        System.out.println(lfuCache.get(79));
        lfuCache.set(41, 71);
        lfuCache.set(94, 111);
        lfuCache.set(19, 124);
        lfuCache.set(52, 70);
        System.out.println(lfuCache.get(131));
        System.out.println(lfuCache.get(103));
        System.out.println(lfuCache.get(81));
        System.out.println(lfuCache.get(126));
        lfuCache.set(61, 279);
        lfuCache.set(37, 100);
        System.out.println(lfuCache.get(95));
        System.out.println(lfuCache.get(54));
        lfuCache.set(59, 136);
        lfuCache.set(101, 219);
        lfuCache.set(15, 248);
        lfuCache.set(37, 91);
        lfuCache.set(11, 174);
        lfuCache.set(99, 65);
        lfuCache.set(105, 249);
        System.out.println(lfuCache.get(85));
        lfuCache.set(108, 287);
        lfuCache.set(96, 4);
        System.out.println(lfuCache.get(70));
        System.out.println(lfuCache.get(24));
        lfuCache.set(52, 206);
        lfuCache.set(59, 306);
        lfuCache.set(18, 296);
        lfuCache.set(79, 95);
        lfuCache.set(50, 131);
        lfuCache.set(3, 161);
        lfuCache.set(2, 229);
        lfuCache.set(39, 183);
        lfuCache.set(90, 225);
        lfuCache.set(75, 23);
        lfuCache.set(136, 280);
        System.out.println(lfuCache.get(119));
        lfuCache.set(81, 272);
        System.out.println(lfuCache.get(106));
        System.out.println(lfuCache.get(106));
        System.out.println(lfuCache.get(70));
        lfuCache.set(73, 60);
        lfuCache.set(19, 250);
        lfuCache.set(82, 291);
        lfuCache.set(117, 53);
        lfuCache.set(16, 176);
        System.out.println(lfuCache.get(40));
        lfuCache.set(7, 70);
        lfuCache.set(135, 212);
        System.out.println(lfuCache.get(59));
        lfuCache.set(81, 201);
        lfuCache.set(75, 305);
        System.out.println(lfuCache.get(101));
        lfuCache.set(8, 250);
        System.out.println(lfuCache.get(38));
        lfuCache.set(28, 220);
        System.out.println(lfuCache.get(21));
        lfuCache.set(105, 266);
        System.out.println(lfuCache.get(105));
        System.out.println(lfuCache.get(85));
        System.out.println(lfuCache.get(55));
        System.out.println(lfuCache.get(6));
        lfuCache.set(78, 83);
        System.out.println(lfuCache.get(126));
        System.out.println(lfuCache.get(102));
        System.out.println(lfuCache.get(66));
        lfuCache.set(61, 42);
        lfuCache.set(127, 35);
        lfuCache.set(117, 105);
        System.out.println(lfuCache.get(128));
        System.out.println(lfuCache.get(102));
        System.out.println(lfuCache.get(50));
        lfuCache.set(24, 133);
        lfuCache.set(40, 178);
        lfuCache.set(78, 157);
        lfuCache.set(71, 22);
        System.out.println(lfuCache.get(25));
        System.out.println(lfuCache.get(82));
        System.out.println(lfuCache.get(129));
        lfuCache.set(126, 12);
        System.out.println(lfuCache.get(45));
        System.out.println(lfuCache.get(40));
        System.out.println(lfuCache.get(86));
        System.out.println(lfuCache.get(100));
        lfuCache.set(30, 110);
        System.out.println(lfuCache.get(49));
        lfuCache.set(47, 185);
        lfuCache.set(123, 101);
        System.out.println(lfuCache.get(102));
        System.out.println(lfuCache.get(5));
        lfuCache.set(40, 267);
        lfuCache.set(48, 155);
        System.out.println(lfuCache.get(108));
        System.out.println(lfuCache.get(45));
        lfuCache.set(14, 182);
        lfuCache.set(20, 117);
        lfuCache.set(43, 124);
        System.out.println(lfuCache.get(38));
        lfuCache.set(77, 158);
        System.out.println(lfuCache.get(111));
        System.out.println(lfuCache.get(39));
        lfuCache.set(69, 126);
        lfuCache.set(113, 199);
        lfuCache.set(21, 216);
        System.out.println(lfuCache.get(11));
        lfuCache.set(117, 207);
        System.out.println(lfuCache.get(30));
        lfuCache.set(97, 84);
        System.out.println(lfuCache.get(109));
        lfuCache.set(99, 218);
        System.out.println(lfuCache.get(109));
        lfuCache.set(113, 1);
        System.out.println(lfuCache.get(62));
        lfuCache.set(49, 89);
        lfuCache.set(53, 311);
        System.out.println(lfuCache.get(126));
        lfuCache.set(32, 153);
        lfuCache.set(14, 296);
        System.out.println(lfuCache.get(22));
        lfuCache.set(14, 225);
        System.out.println(lfuCache.get(49));
        System.out.println(lfuCache.get(75));
        lfuCache.set(61, 241);
        System.out.println(lfuCache.get(7));
        System.out.println(lfuCache.get(6));
        System.out.println(lfuCache.get(31));
        lfuCache.set(75, 15);
        System.out.println(lfuCache.get(115));
        lfuCache.set(84, 181);
        lfuCache.set(125, 111);
        lfuCache.set(105, 94);
        lfuCache.set(48, 294);
        System.out.println(lfuCache.get(106));
        System.out.println(lfuCache.get(61));
        lfuCache.set(53, 190);
        System.out.println(lfuCache.get(16));
        lfuCache.set(12, 252);
        System.out.println(lfuCache.get(28));
        lfuCache.set(111, 122);
        System.out.println(lfuCache.get(122));
        lfuCache.set(10, 21);
        System.out.println(lfuCache.get(59));
        System.out.println(lfuCache.get(72));
        System.out.println(lfuCache.get(39));
        System.out.println(lfuCache.get(6));
        System.out.println(lfuCache.get(126));
        lfuCache.set(131, 177);
        lfuCache.set(105, 253);
        System.out.println(lfuCache.get(26));
        lfuCache.set(43, 311);
        System.out.println(lfuCache.get(79));
        lfuCache.set(91, 32);
        lfuCache.set(7, 141);
        System.out.println(lfuCache.get(38));
        System.out.println(lfuCache.get(13));
        lfuCache.set(79, 135);
        System.out.println(lfuCache.get(43));
        System.out.println(lfuCache.get(94));
        lfuCache.set(80, 182);
        System.out.println(lfuCache.get(53));
        lfuCache.set(120, 309);
        lfuCache.set(3, 109);
        System.out.println(lfuCache.get(97));
        lfuCache.set(9, 128);
        lfuCache.set(114, 121);
        System.out.println(lfuCache.get(56));
        System.out.println(lfuCache.get(56));
        lfuCache.set(124, 86);
        lfuCache.set(34, 145);
        System.out.println(lfuCache.get(131));
        System.out.println(lfuCache.get(78));
        lfuCache.set(86, 21);
        System.out.println(lfuCache.get(98));
        lfuCache.set(115, 164);
        lfuCache.set(47, 225);
        System.out.println(lfuCache.get(95));
        lfuCache.set(89, 55);
        lfuCache.set(26, 134);
        lfuCache.set(8, 15);
        System.out.println(lfuCache.get(11));
        lfuCache.set(84, 276);
        lfuCache.set(81, 67);
        System.out.println(lfuCache.get(46));
        System.out.println(lfuCache.get(39));
        System.out.println(lfuCache.get(92));
        System.out.println(lfuCache.get(96));
        lfuCache.set(89, 51);
        lfuCache.set(136, 240);
        System.out.println(lfuCache.get(45));
        System.out.println(lfuCache.get(27));
        lfuCache.set(24, 209);
        lfuCache.set(82, 145);
        System.out.println(lfuCache.get(10));
        lfuCache.set(104, 225);
        lfuCache.set(120, 203);
        lfuCache.set(121, 108);
        lfuCache.set(11, 47);
        System.out.println(lfuCache.get(89));
        lfuCache.set(80, 66);
        System.out.println(lfuCache.get(16));
        lfuCache.set(95, 101);
        System.out.println(lfuCache.get(49));
        System.out.println(lfuCache.get(1));
        lfuCache.set(77, 184);
        System.out.println(lfuCache.get(27));
        lfuCache.set(74, 313);
        lfuCache.set(14, 118);
        System.out.println(lfuCache.get(16));
        System.out.println(lfuCache.get(74));
        lfuCache.set(88, 251);
        System.out.println(lfuCache.get(124));
        lfuCache.set(58, 101);
        lfuCache.set(42, 81);
        System.out.println(lfuCache.get(2));
        lfuCache.set(133, 101);
        System.out.println(lfuCache.get(16));
        lfuCache.set(1, 254);
        lfuCache.set(25, 167);
        lfuCache.set(53, 56);
        lfuCache.set(73, 198);
        System.out.println(lfuCache.get(48));
        System.out.println(lfuCache.get(30));
        System.out.println(lfuCache.get(95));
        lfuCache.set(90, 102);
        lfuCache.set(92, 56);
        lfuCache.set(2, 130);
        lfuCache.set(52, 11);
        System.out.println(lfuCache.get(9));
        System.out.println(lfuCache.get(23));
        lfuCache.set(53, 275);
        lfuCache.set(23, 258);
        System.out.println(lfuCache.get(57));
        lfuCache.set(136, 183);
        lfuCache.set(75, 265);
        System.out.println(lfuCache.get(85));
        lfuCache.set(68, 274);
        lfuCache.set(15, 255);
        System.out.println(lfuCache.get(85));
        lfuCache.set(33, 314);
        lfuCache.set(101, 223);
        lfuCache.set(39, 248);
        lfuCache.set(18, 261);
        lfuCache.set(37, 160);
        System.out.println(lfuCache.get(112));
        System.out.println(lfuCache.get(65));
        lfuCache.set(31, 240);
        lfuCache.set(40, 295);
        lfuCache.set(99, 231);
        System.out.println(lfuCache.get(123));
        lfuCache.set(34, 43);
        System.out.println(lfuCache.get(87));
        System.out.println(lfuCache.get(80));
        lfuCache.set(47, 279);
        lfuCache.set(89, 299);
        System.out.println(lfuCache.get(72));
        lfuCache.set(26, 277);
        lfuCache.set(92, 13);
        lfuCache.set(46, 92);
        lfuCache.set(67, 163);
        lfuCache.set(85, 184);
        System.out.println(lfuCache.get(38));
        lfuCache.set(35, 65);
        System.out.println(lfuCache.get(70));
        System.out.println(lfuCache.get(81));
        lfuCache.set(40, 65);
        System.out.println(lfuCache.get(80));
        lfuCache.set(80, 23);
        lfuCache.set(76, 258);
        System.out.println(lfuCache.get(69));
        System.out.println(lfuCache.get(133));
        lfuCache.set(123, 196);
        lfuCache.set(119, 212);
        lfuCache.set(13, 150);
        lfuCache.set(22, 52);
        lfuCache.set(20, 105);
        lfuCache.set(61, 233);
        System.out.println(lfuCache.get(97));
        lfuCache.set(128, 307);
        System.out.println(lfuCache.get(85));
        System.out.println(lfuCache.get(80));
        System.out.println(lfuCache.get(73));
        System.out.println(lfuCache.get(30));
        lfuCache.set(46, 44);
        System.out.println(lfuCache.get(95));
        lfuCache.set(121, 211);
        lfuCache.set(48, 307);
        System.out.println(lfuCache.get(2));
        lfuCache.set(27, 166);
        System.out.println(lfuCache.get(50));
        lfuCache.set(75, 41);
        lfuCache.set(101, 105);
        System.out.println(lfuCache.get(2));
        lfuCache.set(110, 121);
        lfuCache.set(32, 88);
        lfuCache.set(75, 84);
        lfuCache.set(30, 165);
        lfuCache.set(41, 142);
        lfuCache.set(128, 102);
        lfuCache.set(105, 90);
        lfuCache.set(86, 68);
        lfuCache.set(13, 292);
        lfuCache.set(83, 63);
        lfuCache.set(5, 239);
        System.out.println(lfuCache.get(5));
        lfuCache.set(68, 204);
        System.out.println(lfuCache.get(127));
        lfuCache.set(42, 137);
        System.out.println(lfuCache.get(93));
        lfuCache.set(90, 258);
        lfuCache.set(40, 275);
        lfuCache.set(7, 96);
        System.out.println(lfuCache.get(108));
        lfuCache.set(104, 91);
        System.out.println(lfuCache.get(63));
        System.out.println(lfuCache.get(31));
        lfuCache.set(31, 89);
        System.out.println(lfuCache.get(74));
        System.out.println(lfuCache.get(81));
        lfuCache.set(126, 148);
        System.out.println(lfuCache.get(107));
        lfuCache.set(13, 28);
        lfuCache.set(21, 139);
        System.out.println(lfuCache.get(114));
        System.out.println(lfuCache.get(5));
        System.out.println(lfuCache.get(89));
        System.out.println(lfuCache.get(133));
        System.out.println(lfuCache.get(20));
        lfuCache.set(96, 135);
        lfuCache.set(86, 100);
        lfuCache.set(83, 75);
        System.out.println(lfuCache.get(14));
        lfuCache.set(26, 195);
        System.out.println(lfuCache.get(37));
        lfuCache.set(1, 287);
        System.out.println(lfuCache.get(79));
        System.out.println(lfuCache.get(15));
        System.out.println(lfuCache.get(6));
        lfuCache.set(68, 11);
        System.out.println(lfuCache.get(52));
        lfuCache.set(124, 80);
        lfuCache.set(123, 277);
        lfuCache.set(99, 281);
        System.out.println(lfuCache.get(133));
        System.out.println(lfuCache.get(90));
        System.out.println(lfuCache.get(45));
        System.out.println(lfuCache.get(127));
        lfuCache.set(9, 68);
        lfuCache.set(123, 6);
        lfuCache.set(124, 251);
        lfuCache.set(130, 191);
        lfuCache.set(23, 174);
        lfuCache.set(69, 295);
        System.out.println(lfuCache.get(32));
        System.out.println(lfuCache.get(37));
        lfuCache.set(1, 64);
        lfuCache.set(48, 116);
        System.out.println(lfuCache.get(68));
        lfuCache.set(117, 173);
        lfuCache.set(16, 89);
        System.out.println(lfuCache.get(84));
        lfuCache.set(28, 234);
        System.out.println(lfuCache.get(129));
        System.out.println(lfuCache.get(89));
        System.out.println(lfuCache.get(55));
        System.out.println(lfuCache.get(83));
        lfuCache.set(99, 264);
        System.out.println(lfuCache.get(129));
        System.out.println(lfuCache.get(84));
        System.out.println(lfuCache.get(14));
        lfuCache.set(26, 274);
        System.out.println(lfuCache.get(109));
        System.out.println(lfuCache.get(110));
        lfuCache.set(96, 120);
        lfuCache.set(128, 207);
        System.out.println(lfuCache.get(12));
        lfuCache.set(99, 233);
        lfuCache.set(20, 305);
        lfuCache.set(26, 24);
        lfuCache.set(102, 32);
        System.out.println(lfuCache.get(82));
        lfuCache.set(16, 30);
        lfuCache.set(5, 244);
        System.out.println(lfuCache.get(130));
        lfuCache.set(109, 36);
        lfuCache.set(134, 162);
        lfuCache.set(13, 165);
        lfuCache.set(45, 235);
        lfuCache.set(112, 80);
        System.out.println(lfuCache.get(6));
        lfuCache.set(34, 98);
        lfuCache.set(64, 250);
        lfuCache.set(18, 237);
        lfuCache.set(72, 21);
        lfuCache.set(42, 105);
        lfuCache.set(57, 108);
        lfuCache.set(28, 229);
        System.out.println(lfuCache.get(83));
        lfuCache.set(1, 34);
        lfuCache.set(93, 151);
        lfuCache.set(132, 94);
        lfuCache.set(18, 24);
        lfuCache.set(57, 68);
        lfuCache.set(42, 137);
        System.out.println(lfuCache.get(35));
        System.out.println(lfuCache.get(80));
        lfuCache.set(10, 288);
        System.out.println(lfuCache.get(21));
        System.out.println(lfuCache.get(115));
        System.out.println(lfuCache.get(131));
        System.out.println(lfuCache.get(30));
        System.out.println(lfuCache.get(43));
        lfuCache.set(97, 262);
        lfuCache.set(55, 146);
        lfuCache.set(81, 112);
        lfuCache.set(2, 212);
        lfuCache.set(5, 312);
        lfuCache.set(82, 107);
        lfuCache.set(14, 151);
        System.out.println(lfuCache.get(77));
        lfuCache.set(60, 42);
        lfuCache.set(90, 309);
        System.out.println(lfuCache.get(90));
        lfuCache.set(131, 220);
        System.out.println(lfuCache.get(86));
        lfuCache.set(106, 85);
        lfuCache.set(85, 254);
        System.out.println(lfuCache.get(14));
        lfuCache.set(66, 262);
        lfuCache.set(88, 243);
        System.out.println(lfuCache.get(3));
        lfuCache.set(50, 301);
        lfuCache.set(118, 91);
        System.out.println(lfuCache.get(25));
        System.out.println(lfuCache.get(105));
        System.out.println(lfuCache.get(100));
        System.out.println(lfuCache.get(89));
        lfuCache.set(111, 152);
        lfuCache.set(65, 24);
        lfuCache.set(41, 264);
        System.out.println(lfuCache.get(117));
        System.out.println(lfuCache.get(117));
        lfuCache.set(80, 45);
        System.out.println(lfuCache.get(38));
        lfuCache.set(11, 151);
        lfuCache.set(126, 203);
        lfuCache.set(128, 59);
        lfuCache.set(6, 129);
        System.out.println(lfuCache.get(91));
        lfuCache.set(118, 2);
        lfuCache.set(50, 164);
        System.out.println(lfuCache.get(74));
        System.out.println(lfuCache.get(80));
        lfuCache.set(48, 308);
        lfuCache.set(109, 82);
        lfuCache.set(3, 48);
        lfuCache.set(123, 10);
        lfuCache.set(59, 249);
        lfuCache.set(128, 64);
        lfuCache.set(41, 287);
        lfuCache.set(52, 278);
        lfuCache.set(98, 151);
        System.out.println(lfuCache.get(12));
        System.out.println(lfuCache.get(25));
        lfuCache.set(18, 254);
        lfuCache.set(24, 40);
        System.out.println(lfuCache.get(119));
        lfuCache.set(66, 44);
        lfuCache.set(61, 19);
        lfuCache.set(80, 132);
        lfuCache.set(62, 111);
        System.out.println(lfuCache.get(80));
        lfuCache.set(57, 188);
        System.out.println(lfuCache.get(132));
        System.out.println(lfuCache.get(42));
        lfuCache.set(18, 314);
        System.out.println(lfuCache.get(48));
        lfuCache.set(86, 138);
        System.out.println(lfuCache.get(8));
        lfuCache.set(27, 88);
        lfuCache.set(96, 178);
        lfuCache.set(17, 104);
        lfuCache.set(112, 86);
        System.out.println(lfuCache.get(25));
        lfuCache.set(129, 119);
        lfuCache.set(93, 44);
        System.out.println(lfuCache.get(115));
        lfuCache.set(33, 36);
        lfuCache.set(85, 190);
        System.out.println(lfuCache.get(10));
        lfuCache.set(52, 182);
        lfuCache.set(76, 182);
        System.out.println(lfuCache.get(109));
        System.out.println(lfuCache.get(118));
        lfuCache.set(82, 301);
        lfuCache.set(26, 158);
        System.out.println(lfuCache.get(71));
        lfuCache.set(108, 309);
        lfuCache.set(58, 132);
        lfuCache.set(13, 299);
        lfuCache.set(117, 183);
        System.out.println(lfuCache.get(115));
        System.out.println(lfuCache.get(89));
        System.out.println(lfuCache.get(42));
        lfuCache.set(11, 285);
        lfuCache.set(30, 144);
        System.out.println(lfuCache.get(69));
        lfuCache.set(31, 53);
        System.out.println(lfuCache.get(21));
        lfuCache.set(96, 162);
        lfuCache.set(4, 227);
        lfuCache.set(77, 120);
        lfuCache.set(128, 136);
        System.out.println(lfuCache.get(92));
        lfuCache.set(119, 208);
        lfuCache.set(87, 61);
        lfuCache.set(9, 40);
        lfuCache.set(48, 273);
        System.out.println(lfuCache.get(95));
        System.out.println(lfuCache.get(35));
        lfuCache.set(62, 267);
        lfuCache.set(88, 161);
        System.out.println(lfuCache.get(59));
        System.out.println(lfuCache.get(85));
        lfuCache.set(131, 53);
        lfuCache.set(114, 98);
        lfuCache.set(90, 257);
        lfuCache.set(108, 46);
        System.out.println(lfuCache.get(54));
        lfuCache.set(128, 223);
        lfuCache.set(114, 168);
        lfuCache.set(89, 203);
        System.out.println(lfuCache.get(100));
        System.out.println(lfuCache.get(116));
        System.out.println(lfuCache.get(14));
        lfuCache.set(61, 104);
        lfuCache.set(44, 161);
        lfuCache.set(60, 132);
        lfuCache.set(21, 310);
        System.out.println(lfuCache.get(89));
        lfuCache.set(109, 237);
        System.out.println(lfuCache.get(105));
        System.out.println(lfuCache.get(32));
        lfuCache.set(78, 101);
        lfuCache.set(14, 71);
        lfuCache.set(100, 47);
        lfuCache.set(102, 33);
        lfuCache.set(44, 29);
        System.out.println(lfuCache.get(85));
        System.out.println(lfuCache.get(37));
        lfuCache.set(68, 175);
        lfuCache.set(116, 182);
        lfuCache.set(42, 47);
        System.out.println(lfuCache.get(9));
        lfuCache.set(64, 37);
        lfuCache.set(23, 32);
        lfuCache.set(11, 124);
        lfuCache.set(130, 189);
        System.out.println(lfuCache.get(65));
        lfuCache.set(33, 219);
        lfuCache.set(79, 253);
        System.out.println(lfuCache.get(80));
        System.out.println(lfuCache.get(16));
        lfuCache.set(38, 18);
        lfuCache.set(35, 67);
        System.out.println(lfuCache.get(107));
        System.out.println(lfuCache.get(88));
        lfuCache.set(37, 13);
        lfuCache.set(71, 188);
        System.out.println(lfuCache.get(35));
        lfuCache.set(58, 268);
        lfuCache.set(18, 260);
        lfuCache.set(73, 23);
        lfuCache.set(28, 102);
        System.out.println(lfuCache.get(129));
        System.out.println(lfuCache.get(88));
        System.out.println(lfuCache.get(65));
        System.out.println(lfuCache.get(80));
        lfuCache.set(119, 146);
        System.out.println(lfuCache.get(113));
        System.out.println(lfuCache.get(62));
        lfuCache.set(123, 138);
        lfuCache.set(18, 1);
        lfuCache.set(26, 208);
        System.out.println(lfuCache.get(107));
        System.out.println(lfuCache.get(107));
        lfuCache.set(76, 132);
        lfuCache.set(121, 191);
        System.out.println(lfuCache.get(4));
        System.out.println(lfuCache.get(8));
        System.out.println(lfuCache.get(117));
        lfuCache.set(11, 118);
        System.out.println(lfuCache.get(43));
        System.out.println(lfuCache.get(69));
        System.out.println(lfuCache.get(136));
        lfuCache.set(66, 298);
        System.out.println(lfuCache.get(25));
        System.out.println(lfuCache.get(71));
        System.out.println(lfuCache.get(100));
        lfuCache.set(26, 141);
        lfuCache.set(53, 256);
        lfuCache.set(111, 205);
        lfuCache.set(126, 106);
        System.out.println(lfuCache.get(43));
        lfuCache.set(14, 39);
        lfuCache.set(44, 41);
        lfuCache.set(23, 230);
        System.out.println(lfuCache.get(131));
        System.out.println(lfuCache.get(53));
        lfuCache.set(104, 268);
        System.out.println(lfuCache.get(30));
        lfuCache.set(108, 48);
        lfuCache.set(72, 45);
        System.out.println(lfuCache.get(58));
        System.out.println(lfuCache.get(46));
        lfuCache.set(128, 301);
        System.out.println(lfuCache.get(71));
        System.out.println(lfuCache.get(99));
        System.out.println(lfuCache.get(113));
        System.out.println(lfuCache.get(121));
        lfuCache.set(130, 122);
        lfuCache.set(102, 5);
        lfuCache.set(111, 51);
        lfuCache.set(85, 229);
        lfuCache.set(86, 157);
        lfuCache.set(82, 283);
        lfuCache.set(88, 52);
        lfuCache.set(136, 105);
        System.out.println(lfuCache.get(40));
        System.out.println(lfuCache.get(63));
        lfuCache.set(114, 244);
        lfuCache.set(29, 82);
        lfuCache.set(83, 278);
        System.out.println(lfuCache.get(131));
        lfuCache.set(56, 33);
        System.out.println(lfuCache.get(123));
        System.out.println(lfuCache.get(11));
        System.out.println(lfuCache.get(119));
        lfuCache.set(119, 1);
        lfuCache.set(48, 52);
        System.out.println(lfuCache.get(47));
        lfuCache.set(127, 136);
        lfuCache.set(78, 38);
        lfuCache.set(117, 64);
        lfuCache.set(130, 134);
        lfuCache.set(93, 69);
        lfuCache.set(70, 98);
        System.out.println(lfuCache.get(68));
        lfuCache.set(4, 3);
        lfuCache.set(92, 173);
        lfuCache.set(114, 65);
        lfuCache.set(7, 309);
        System.out.println(lfuCache.get(31));
        lfuCache.set(107, 271);
        lfuCache.set(110, 69);
        System.out.println(lfuCache.get(45));
        lfuCache.set(35, 288);
        System.out.println(lfuCache.get(20));
        lfuCache.set(38, 79);
        System.out.println(lfuCache.get(46));
        lfuCache.set(6, 123);
        System.out.println(lfuCache.get(19));
        lfuCache.set(84, 95);
        System.out.println(lfuCache.get(76));
        lfuCache.set(71, 31);
        lfuCache.set(72, 171);
        lfuCache.set(35, 123);
        System.out.println(lfuCache.get(32));
        lfuCache.set(73, 85);
        System.out.println(lfuCache.get(94));
        System.out.println(lfuCache.get(128));
        System.out.println(lfuCache.get(28));
        System.out.println(lfuCache.get(38));
        System.out.println(lfuCache.get(109));
        lfuCache.set(85, 197);
        lfuCache.set(10, 41);
        lfuCache.set(71, 50);
        System.out.println(lfuCache.get(128));
        lfuCache.set(3, 55);
        lfuCache.set(15, 9);
        lfuCache.set(127, 215);
        System.out.println(lfuCache.get(17));
        System.out.println(lfuCache.get(37));
        lfuCache.set(111, 272);
        lfuCache.set(79, 169);
        lfuCache.set(86, 206);
        lfuCache.set(40, 264);
        System.out.println(lfuCache.get(134));
        lfuCache.set(16, 207);
        lfuCache.set(27, 127);
        lfuCache.set(29, 48);
        lfuCache.set(32, 122);
        lfuCache.set(15, 35);
        lfuCache.set(117, 36);
        System.out.println(lfuCache.get(127));
        System.out.println(lfuCache.get(36));
        lfuCache.set(72, 70);
        lfuCache.set(49, 201);
        lfuCache.set(89, 215);
        lfuCache.set(134, 290);
        lfuCache.set(77, 64);
        lfuCache.set(26, 101);
        System.out.println(lfuCache.get(99));
        lfuCache.set(36, 96);
        lfuCache.set(84, 129);
        lfuCache.set(125, 264);
        System.out.println(lfuCache.get(43));
        System.out.println(lfuCache.get(38));
        lfuCache.set(24, 76);
        lfuCache.set(45, 2);
        lfuCache.set(32, 24);
        lfuCache.set(84, 235);
        lfuCache.set(16, 240);
        lfuCache.set(17, 289);
        lfuCache.set(49, 94);
        lfuCache.set(90, 54);
        lfuCache.set(88, 199);
        System.out.println(lfuCache.get(23));
        lfuCache.set(87, 19);
        lfuCache.set(11, 19);
        System.out.println(lfuCache.get(24));
        System.out.println(lfuCache.get(57));
        System.out.println(lfuCache.get(4));
        System.out.println(lfuCache.get(40));
        lfuCache.set(133, 286);
        lfuCache.set(127, 231);
        System.out.println(lfuCache.get(51));
        lfuCache.set(52, 196);
        System.out.println(lfuCache.get(27));
        System.out.println(lfuCache.get(10));
        System.out.println(lfuCache.get(93));
        lfuCache.set(115, 143);
        lfuCache.set(62, 64);
        lfuCache.set(59, 200);
        lfuCache.set(75, 85);
        lfuCache.set(7, 93);
        lfuCache.set(117, 270);
        lfuCache.set(116, 6);
        System.out.println(lfuCache.get(32));
        System.out.println(lfuCache.get(135));
        lfuCache.set(2, 140);
        lfuCache.set(23, 1);
        lfuCache.set(11, 69);
        lfuCache.set(89, 30);
        lfuCache.set(27, 14);
        System.out.println(lfuCache.get(100));
        System.out.println(lfuCache.get(61));
        lfuCache.set(99, 41);
        lfuCache.set(88, 12);
        System.out.println(lfuCache.get(41));
        lfuCache.set(52, 203);
        System.out.println(lfuCache.get(65));
        lfuCache.set(62, 78);
        lfuCache.set(104, 276);
        lfuCache.set(105, 307);
        System.out.println(lfuCache.get(7));
        lfuCache.set(23, 123);
        System.out.println(lfuCache.get(22));
        lfuCache.set(35, 299);
        System.out.println(lfuCache.get(69));
        System.out.println(lfuCache.get(11));
        lfuCache.set(14, 112);
        System.out.println(lfuCache.get(115));
        System.out.println(lfuCache.get(112));
        System.out.println(lfuCache.get(108));
        lfuCache.set(110, 165);
        lfuCache.set(83, 165);
        lfuCache.set(36, 260);
        lfuCache.set(54, 73);
        System.out.println(lfuCache.get(36));
        lfuCache.set(93, 69);
        System.out.println(lfuCache.get(134));
        lfuCache.set(125, 96);
        lfuCache.set(74, 127);
        lfuCache.set(110, 305);
        lfuCache.set(92, 309);
        lfuCache.set(87, 45);
        lfuCache.set(31, 266);
        System.out.println(lfuCache.get(10));
        lfuCache.set(114, 206);
        lfuCache.set(49, 141);
        System.out.println(lfuCache.get(82));
        lfuCache.set(92, 3);
        lfuCache.set(91, 160);
        System.out.println(lfuCache.get(41));
        lfuCache.set(60, 147);
        lfuCache.set(36, 239);
        lfuCache.set(23, 296);
        lfuCache.set(134, 120);
        System.out.println(lfuCache.get(6));
        lfuCache.set(5, 283);
        lfuCache.set(117, 68);
        System.out.println(lfuCache.get(35));
        System.out.println(lfuCache.get(120));
        lfuCache.set(44, 191);
        lfuCache.set(121, 14);
        lfuCache.set(118, 113);
        lfuCache.set(84, 106);
        System.out.println(lfuCache.get(23));
        lfuCache.set(15, 240);
        System.out.println(lfuCache.get(37));
        lfuCache.set(52, 256);
        lfuCache.set(119, 116);
        lfuCache.set(101, 7);
        lfuCache.set(14, 157);
        lfuCache.set(29, 225);
        lfuCache.set(4, 247);
        lfuCache.set(8, 112);
        lfuCache.set(8, 189);
        lfuCache.set(96, 220);
        System.out.println(lfuCache.get(104));
        lfuCache.set(72, 106);
        lfuCache.set(23, 170);
        lfuCache.set(67, 209);
        lfuCache.set(70, 39);
        System.out.println(lfuCache.get(18));
        System.out.println(lfuCache.get(6));
        System.out.println(lfuCache.get(34));
        lfuCache.set(121, 157);
        System.out.println(lfuCache.get(16));
        System.out.println(lfuCache.get(19));
        lfuCache.set(83, 283);
        lfuCache.set(13, 22);
        lfuCache.set(33, 143);
        lfuCache.set(88, 133);
        System.out.println(lfuCache.get(88));
        lfuCache.set(5, 49);
        System.out.println(lfuCache.get(38));
        System.out.println(lfuCache.get(110));
        System.out.println(lfuCache.get(67));
        lfuCache.set(23, 227);
        System.out.println(lfuCache.get(68));
        System.out.println(lfuCache.get(3));
        lfuCache.set(27, 265);
        System.out.println(lfuCache.get(31));
        lfuCache.set(13, 103);
        System.out.println(lfuCache.get(116));
        lfuCache.set(111, 282);
        lfuCache.set(43, 71);
        System.out.println(lfuCache.get(134));
        lfuCache.set(70, 141);
        System.out.println(lfuCache.get(14));
        System.out.println(lfuCache.get(119));
        System.out.println(lfuCache.get(43));
        System.out.println(lfuCache.get(122));
        lfuCache.set(38, 187);
        lfuCache.set(8, 9);
        System.out.println(lfuCache.get(63));
        lfuCache.set(42, 140);
        System.out.println(lfuCache.get(83));
        System.out.println(lfuCache.get(92));
        System.out.println(lfuCache.get(106));
        System.out.println(lfuCache.get(28));
        lfuCache.set(57, 139);
        lfuCache.set(36, 257);
        lfuCache.set(30, 204);
        System.out.println(lfuCache.get(72));
        lfuCache.set(105, 243);
        System.out.println(lfuCache.get(16));
        lfuCache.set(74, 25);
        System.out.println(lfuCache.get(22));
        lfuCache.set(118, 144);
        System.out.println(lfuCache.get(133));
        System.out.println(lfuCache.get(71));
        lfuCache.set(99, 21);
        System.out.println(lfuCache.get(26));
        System.out.println(lfuCache.get(35));
        lfuCache.set(89, 209);
        lfuCache.set(106, 158);
        lfuCache.set(76, 63);
        lfuCache.set(112, 216);
        System.out.println(lfuCache.get(128));
        System.out.println(lfuCache.get(54));
        lfuCache.set(16, 165);
        lfuCache.set(76, 206);
        lfuCache.set(69, 253);
        System.out.println(lfuCache.get(23));
        lfuCache.set(54, 111);
        System.out.println(lfuCache.get(80));
        lfuCache.set(111, 72);
        lfuCache.set(95, 217);
        System.out.println(lfuCache.get(118));
        lfuCache.set(4, 146);
        System.out.println(lfuCache.get(47));
        lfuCache.set(108, 290);
        System.out.println(lfuCache.get(43));
        lfuCache.set(70, 8);
        System.out.println(lfuCache.get(117));
        System.out.println(lfuCache.get(121));
        lfuCache.set(42, 220);
        System.out.println(lfuCache.get(48));
        System.out.println(lfuCache.get(32));
        lfuCache.set(68, 213);
        lfuCache.set(30, 157);
        lfuCache.set(62, 68);
        System.out.println(lfuCache.get(58));
        lfuCache.set(125, 283);
        lfuCache.set(132, 45);
        System.out.println(lfuCache.get(85));
        System.out.println(lfuCache.get(92));
        lfuCache.set(23, 257);
        System.out.println(lfuCache.get(74));
        lfuCache.set(18, 256);
        System.out.println(lfuCache.get(90));
        lfuCache.set(10, 158);
        lfuCache.set(57, 34);
        System.out.println(lfuCache.get(27));
        System.out.println(lfuCache.get(107));
    }
}